# Generated by Django 5.0.7 on 2024-08-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
