# Generated by Django 5.0.7 on 2024-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
