# Generated by Django 5.0.7 on 2024-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
